used docker login instead of acr login

diff --git a/.github/workflows/aks-helm-cicd.yml b/.github/workflows/aks-helm-cicd.yml
--- a/.github/workflows/aks-helm-cicd.yml
+++ b/.github/workflows/aks-helm-cicd.yml
@@ -51,9 +51,14 @@ jobs:
         with:
           creds: ${{ secrets.AZURE_CREDENTIALS }}
 
-      # ---------- ACR login ----------
-      - name: ACR login
-        run: az acr login -n "$ACR_NAME"
+      - name: Docker Login to ACR
+        run: |
+          set -e  # Exit immediately if any command here fails
+          echo "Logging in directly to $ACR_LOGIN_SERVER..."
+          docker login $ACR_LOGIN_SERVER \
+            -u ${{ fromJson(secrets.AZURE_CREDENTIALS).clientId }} \
+            -p ${{ fromJson(secrets.AZURE_CREDENTIALS).clientSecret }}
+
 
       # ---------- Build & push images (only when sources changed) ----------
       - name: Build & Push BACKEND image
